Repository movementlabsxyz/movement, pull requests merged in 2025-03, with the labels that each got.

#1072 fix: add back labeled builds
  .github/workflows/build-push-containers-all.yml
  .github/workflows/checks-all.yml
  .github/workflows/hsm-demo-containers.yml
Labels: cicd:bridge-containers, cicd:movement-containers

#1094 chore: add back in missing submodule and mrb_cache
  .gitmodules
  protocol-units/execution/maptos/framework/releases/biarritz-rc1/mrb_cache/27397b5835e6a466c06c884a395653c9ff13d1fe-biarritz-rc1.mrb
Labels: cicd:suzuka-containers, cicd:suzuka-full-node, cicd:suzuka-full-node-malicious, cicd:movement-containers, cicd:movement-full-node

#1095 chore: update aptos core rev
  Cargo.toml
Labels: cicd:movement-containers, cicd:movement-full-node

#1150 feat: da-seq persist rocksdb store
  Cargo.lock
  Cargo.toml
  protocol-units/da-sequencer/node/Cargo.toml
  protocol-units/da-sequencer/node/src/batch.rs
  protocol-units/da-sequencer/node/src/block.rs
  protocol-units/da-sequencer/node/src/error.rs
  protocol-units/da-sequencer/node/src/lib.rs
  protocol-units/da-sequencer/node/src/server.rs
  protocol-units/da-sequencer/node/src/storage/mod.rs
  util/movement-types/Cargo.toml
  util/movement-types/src/block.rs
  util/movement-types/src/transaction.rs
Labels: celestia
